version: '1.0'

services:
  shinobi_redis:
    container_name: shinobi_redis
    hostname: shinobi_redis

    image: redis:latest
    restart: always

    volumes:
      - ../redis:/redis

    networks:
      - shinobi_network

    entrypoint: ["redis-server", "/redis/redis.conf"]


  shinobi_bot:
    container_name: shinobi_bot

    image: shinobi:latest
    ports:
      - 9032:9032
    restart: always
    depends_on:
      - shinobi_redis

    env_file: ../.env
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=shinobi_redis
      - API_HOST=shinobi_api
      - SANIC_HOST=shinobi_webserver


    build: 
      dockerfile: deploy_tg/Dockerfile
      context: ..

    networks:
      - shinobi_network


networks:
  shinobi_network:
    external: true